"""empty message

Revision ID: 0cbe1cae7473
Revises: 57b563d2df2d
Create Date: 2025-02-02 22:03:56.543229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbe1cae7473'
down_revision: Union[str, None] = '57b563d2df2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('next_pay_date', sa.Date(), nullable=False))
    op.add_column('credit', sa.Column('percent', sa.Float(), nullable=False))
    op.drop_column('credit', 'next_pay_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('next_pay_data', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('credit', 'percent')
    op.drop_column('credit', 'next_pay_date')
    # ### end Alembic commands ###
