"""init

Revision ID: 80cb8e36587e
Revises: 
Create Date: 2025-01-30 22:52:28.314661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cb8e36587e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_spec', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('passport_serial', sa.Integer(), nullable=False),
    sa.Column('passport_number', sa.Integer(), nullable=False),
    sa.Column('gotten_by', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('registration_address', sa.String(length=255), nullable=False),
    sa.Column('current_job', sa.String(length=255), nullable=False),
    sa.Column('per_month_profit', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('family_status', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user'))
    )
    op.create_index(op.f('ix__user__email'), 'user', ['email'], unique=True)
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_pay_data', sa.Date(), nullable=False),
    sa.Column('remain_to_pay', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_pay', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__credit__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__credit'))
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('credit_size', sa.Float(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__order__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__order'))
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('monthly_pay', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk__response__order_id__order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__response'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('order')
    op.drop_table('credit')
    op.drop_index(op.f('ix__user__email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
